action.configuration.pathauto_update_alias_node:
  type: action_configuration_default
  label: 'Update URL-Alias'
action.configuration.pathauto_update_alias_user:
  type: action_configuration_default
  label: 'Update URL-Alias'
